### ISSUE TITLE
select only relevant urls

### ISSUE THREAD

**Issue by grelf111** [pkramme/sw5cachewarm#1]
Great Idea!
Most URLs in 's_core_rewrite_urls' are seo-history, only used to send a proper '301 Moved Permanently' to search engines. Seo History is used if categories, products, etc. are changed or a complete shop was moved.
The relevant, active urls have the attribute main=1.
The urls with main=0 don't need to be processed. 
In my shop it is 45.000 history urls versus 10.000 active urls.

The queries in line 71/78 should be 
"SELECT * FROM s_core_rewrite_urls where main=1"

In subshop environments the attribute subshopID should be an option:
-subshop long integer
        Shopware Subshop ID

"SELECT * FROM s_core_rewrite_urls where main=1 and subshopID=" & subshopid 
Sorry, don't know the correct syntax  ...

Regards
grelf

**Comment by pkramme** [comment]
Thanks! 

Added in 3a03ad9540e37b84425895480dfeaa17e081f42d
